---
title: "Homework 5"
author: "Courtney Maichak"
date: "12/01/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# Packages
library(tidyverse)
library(tidyr)
library(dplyr)
library(broom)
library(purrr)
library(ggplot2)
library(forcats)
library(ggthemes)
library(lubridate)
```

```{r}
list.files("../data")
```
```{r}
# Reading in data
homicides <- read.csv("homicide-data.csv")

homicides <- homicides %>%
  unite("city_name", city:state, sep = ", ")
```
```{r}
# Filtering Baltimore
baltimore <- homicides %>% 
  filter(city_name == "Baltimore, MD")

baltimore
```
```{r}
# Group by month and year
sum_balt <- baltimore %>%
  mutate(reported_date = ymd(reported_date)) %>%
  mutate(year = year(reported_date)) %>%
  mutate(month = month(reported_date)) %>%
  group_by(year, month) %>%
  count()
  
 sum_balt <- sum_balt %>%
  mutate(date = paste(year, month, "15", sep = "-")) %>%
  mutate(date = ymd(date))
 ```
```{r}
# Separate by cold winter months and warm months
sum_balt <- sum_balt %>%
  mutate(cold_months = month %in% c(11, 12, 1:4)) %>%
  mutate(warm_months = month %in% c(5:10))
  
sum_balt
```
```{r, fig.width=10, fig.height=3}
# Plot data
balt_plot <- sum_balt %>%
  ggplot(aes(x = date, y = n)) +
  geom_col(aes(fill = cold_months)) +
  geom_smooth(span = 0.1, color = "blue", se = FALSE, size = 1) +
  theme_dark() +
  ggtitle("Homicides in Baltimore, MD") +
  labs(y = "Monthly homicides", x = "Date") +
  theme(legend.position = "bottom") +
  scale_fill_manual(values = c("light gray", "light blue"), name = " ", labels = c("Summer", "Winter"))
  
  balt_plot
 ```
